OrdererOrgs:
  - Name: TradeOrderer
    Domain: trade.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: ExporterOrg
    Domain: exporterorg.trade.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: ImporterOrg
    Domain: importerorg.trade.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: CarrierOrg
    Domain: carrierorg.trade.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: RegulatorOrg
    Domain: regulatororg.trade.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

